/**
 * Demo data for showcasing all UI flows.
 * Merged with real API data so both real + fake data appear.
 */

export const DEMO_SITES = [
  {
    _id: 'demo-site-1',
    id: 'demo-site-1',
    name: 'Shell Deer Park Refinery',
    description: 'Tank farm inspection and monitoring',
    thumbnail_url: null,
    latitude: 29.7174,
    longitude: -95.1268,
    tags: ['oil-gas', 'refinery'],
    status: 'active',
    project_count: 3,
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    _id: 'demo-site-2',
    id: 'demo-site-2',
    name: 'Santiago Mining Complex',
    description: 'Open pit volumetric surveys',
    thumbnail_url: null,
    latitude: -33.4489,
    longitude: -70.6693,
    tags: ['mining', 'chile'],
    status: 'active',
    project_count: 2,
    created_at: '2026-03-10T08:00:00Z',
  },
  {
    _id: 'demo-site-3',
    id: 'demo-site-3',
    name: 'Dubai Solar Park',
    description: 'Panel inspection and thermal mapping',
    thumbnail_url: null,
    latitude: 24.7136,
    longitude: 55.0892,
    tags: ['solar', 'inspection'],
    status: 'active',
    project_count: 1,
    created_at: '2026-02-20T12:00:00Z',
  },
];

export const DEMO_PROJECTS: Record<string, any[]> = {
  'demo-site-1': [
    {
      _id: 'demo-proj-1a',
      id: 'demo-proj-1a',
      site_id: 'demo-site-1',
      name: 'Tank Farm A — Weekly Survey',
      description: 'Recurring orthomosaic of tank farm sector A',
      image_count: 148,
      status: 'completed',
      quality: 'high',
      gsd_cm: 1.8,
      area_hectares: 12.4,
      thumbnail_url: null,
      mission_name: 'TF-A Weekly',
      created_at: '2026-03-25T14:00:00Z',
    },
    {
      _id: 'demo-proj-1b',
      id: 'demo-proj-1b',
      site_id: 'demo-site-1',
      name: 'Pipeline Corridor Scan',
      description: 'Linear inspection flight along main pipeline',
      image_count: 86,
      status: 'completed',
      quality: 'medium',
      gsd_cm: 2.5,
      area_hectares: 5.2,
      thumbnail_url: null,
      mission_name: 'Pipeline-01',
      created_at: '2026-03-22T09:00:00Z',
    },
    {
      _id: 'demo-proj-1c',
      id: 'demo-proj-1c',
      site_id: 'demo-site-1',
      name: 'Emergency Response — Leak Detection',
      description: '',
      image_count: 42,
      status: 'processing',
      quality: 'preview',
      gsd_cm: null,
      area_hectares: null,
      thumbnail_url: null,
      mission_name: null,
      created_at: '2026-03-28T16:30:00Z',
    },
  ],
  'demo-site-2': [
    {
      _id: 'demo-proj-2a',
      id: 'demo-proj-2a',
      site_id: 'demo-site-2',
      name: 'Pit #3 Volumetric — March',
      description: 'Monthly stockpile measurement',
      image_count: 210,
      status: 'completed',
      quality: 'high',
      gsd_cm: 2.0,
      area_hectares: 28.0,
      thumbnail_url: null,
      mission_name: 'Pit3-Monthly',
      created_at: '2026-03-20T11:00:00Z',
    },
    {
      _id: 'demo-proj-2b',
      id: 'demo-proj-2b',
      site_id: 'demo-site-2',
      name: 'Haul Road Inspection',
      description: '',
      image_count: 0,
      status: 'created',
      quality: 'medium',
      gsd_cm: null,
      area_hectares: null,
      thumbnail_url: null,
      mission_name: null,
      created_at: '2026-03-28T08:00:00Z',
    },
  ],
  'demo-site-3': [
    {
      _id: 'demo-proj-3a',
      id: 'demo-proj-3a',
      site_id: 'demo-site-3',
      name: 'Solar Array Block D — Thermal',
      description: 'Thermal + RGB dual survey',
      image_count: 320,
      status: 'completed',
      quality: 'high',
      gsd_cm: 1.2,
      area_hectares: 18.0,
      thumbnail_url: null,
      mission_name: 'BlockD-Thermal',
      created_at: '2026-03-18T06:00:00Z',
    },
  ],
};

export const DEMO_JOBS = [
  {
    _id: 'demo-job-1',
    id: 'demo-job-1',
    project_id: 'demo-proj-1a',
    status: 'completed',
    progress: 100,
    stage: 'Complete',
    image_count: 148,
    created_at: '2026-03-25T14:05:00Z',
    completed_at: '2026-03-25T15:15:00Z',
    error: null,
  },
  {
    _id: 'demo-job-2',
    id: 'demo-job-2',
    project_id: 'demo-proj-1b',
    status: 'completed',
    progress: 100,
    stage: 'Complete',
    image_count: 86,
    created_at: '2026-03-22T09:10:00Z',
    completed_at: '2026-03-22T09:52:00Z',
    error: null,
  },
  {
    _id: 'demo-job-3',
    id: 'demo-job-3',
    project_id: 'demo-proj-1c',
    status: 'processing',
    progress: 47,
    stage: 'Generating orthomosaic',
    image_count: 42,
    created_at: '2026-03-28T16:35:00Z',
    completed_at: null,
    error: null,
  },
  {
    _id: 'demo-job-4',
    id: 'demo-job-4',
    project_id: 'demo-proj-2a',
    status: 'completed',
    progress: 100,
    stage: 'Complete',
    image_count: 210,
    created_at: '2026-03-20T11:05:00Z',
    completed_at: '2026-03-20T12:45:00Z',
    error: null,
  },
  {
    _id: 'demo-job-5',
    id: 'demo-job-5',
    project_id: 'demo-proj-3a',
    status: 'failed',
    progress: 68,
    stage: 'ODM crashed',
    image_count: 320,
    created_at: '2026-03-18T06:10:00Z',
    completed_at: null,
    error: 'ODM exited with code 137 — out of memory. Try reducing image count or lowering quality.',
  },
  {
    _id: 'demo-job-6',
    id: 'demo-job-6',
    project_id: 'demo-proj-3a',
    status: 'completed',
    progress: 100,
    stage: 'Complete',
    image_count: 280,
    created_at: '2026-03-19T07:00:00Z',
    completed_at: '2026-03-19T09:20:00Z',
    error: null,
  },
];

// Flight dates for date filter demo (demo-proj-1a has multiple flights)
export const DEMO_FLIGHT_DATES: Record<string, { date: string; flightCount: number; imageCount: number }[]> = {
  'proj001': [
    { date: '2026-03-02', flightCount: 1, imageCount: 72 },
    { date: '2026-03-09', flightCount: 1, imageCount: 68 },
    { date: '2026-03-16', flightCount: 2, imageCount: 140 },
    { date: '2026-03-23', flightCount: 1, imageCount: 75 },
  ],
  'demo-proj-1a': [
    { date: '2026-03-01', flightCount: 1, imageCount: 36 },
    { date: '2026-03-08', flightCount: 1, imageCount: 38 },
    { date: '2026-03-15', flightCount: 2, imageCount: 74 },
    { date: '2026-03-22', flightCount: 1, imageCount: 35 },
    { date: '2026-03-29', flightCount: 1, imageCount: 40 },
  ],
  'demo-proj-2a': [
    { date: '2026-03-05', flightCount: 1, imageCount: 105 },
    { date: '2026-03-20', flightCount: 1, imageCount: 105 },
  ],
};

export function getAllDemoProjects() {
  return Object.values(DEMO_PROJECTS).flat();
}
